### ISSUE TITLE
Anonymous login return inaccurate error description 

### ISSUE THREAD

**Issue by Peter-ChengTszTung** [authgear/authgear-sdk-js#11]
#### Steps:
- Disable `anonymous` authentication at `authgear`
- Attempt anonymous login at client side
   -  `await container.authenticateAnonymously()`
- Log the error

#### Expected Results
```
{
  "error": "server_error",
  "error_description":  "{Message that indicate anonymous login not permitted}"
}
```

#### Actual Results
```
{
  "error": "server_error",
  "error_description": "internal server error",
}
```

**Comment by axolotl0212** [comment]
Backend returns correct error message now

```
failure(Authgear.AuthAPIClientError.oidcError(Authgear.OIDCError(error: "unauthorized_client", errorDescription: "anonymous users are not allowed")))
```

**Comment by axolotl0212** [comment]
Fixed by https://github.com/authgear/authgear-server/blob/master/pkg/lib/interaction/nodes/use_identity_anonymous.go#L40-L46
