### ISSUE TITLE
Implement session state and OnSessionStateChanged equivalent in js

### ISSUE THREAD

**Issue by roxk** [authgear/authgear-sdk-js#16]
Please refer to https://github.com/authgear/authgear-sdk-android/issues/9 for the rationale.

**Comment by axolotl0212** [comment]
Ref: https://github.com/authgear/authgear-sdk-ios/blob/be537a8d4bbbdb6da5680c71fa04ea80fb6789a6/Sources/Authgear.swift#L70

Implement this in JS sdk
