### ISSUE TITLE
v1 breaking changes

### ISSUE THREAD

**Issue by louischan-oursky** [authgear/authgear-sdk-js#190]
- [x] Rename `authorize` to `authenticate`
 - [x] Remove `state` from the return value of react native SDK methods
 - [x] #195

**Comment by louischan-oursky** [comment]
In web, startAuthentication and finishAuthentication needs to accept state because it offers a way for the developer to correlate the state.

In react native, the state is unnecessary because the authenticate() is asynchronous. If state is taken in arguments, it would just be echoed back in the result.

**Comment by carmenlau** [comment]
This is completed and released in [v1.0.1](https://github.com/authgear/authgear-sdk-js/releases/tag/v1.0.1).
