### ISSUE TITLE
Add isAnonymous to user info

### ISSUE THREAD

**Issue by roxk** [authgear/authgear-sdk-js#20]

**Comment by roxk** [comment]
@kiootic What is the best practice to hide the deserialization detail `http://authgear.com/claims/keys/is-anonymous` in ts?

**Comment by kiootic** [comment]
Previously we have conversion function to convert between API models and SDK models: https://github.com/SkygearIO/skygear-SDK-JS/blob/master/packages/skygear-core/src/encoding.ts
We can use the same approach here.
