### ISSUE TITLE
Promoting anonymous users by WeChat Login results in unexpected errors

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-sdk-js#247]
Testing device: iPhone SE (iOS 16.4.1 (a))
App platform: React Native

Reported from a client. [Original Issue](https://github.com/oursky/te-merchant/issues/1421)

**Problem 1:**

Promote anonymous user with a WeChat account that's already connected

- Using the app as an anonymous user
- Triggers promote user
- Select "Login with WeChat"
- proceed with a WeChat user who has already signed up, the WeChat app is opened
- Return to the original app
- it will show unexpected error in AuthUI

<img width="361" alt="image" src="https://github.com/authgear/authgear-sdk-js/assets/15207470/dae9c05c-ea1d-4b5d-8b8c-f575388ee4c6">

**Problem 2:**

- Using the app as an anonymous user
- Triggers promote user
- Select "Login with WeChat"
- WeChat app is killed
- Press "Open WeChat app to login" on AuthUI, the WeChat app is opened
- Return to the original app after loading
- Get a "Network request failed" error

<img width="335" alt="image" src="https://github.com/authgear/authgear-sdk-js/assets/15207470/58cd1f0d-afda-4bc1-8ee8-57de8d965227">

**Problem 3:**

The "Open WeChat app to login" and "Proceed WeChat login" buttons on AuthUI can be pressed multiple time and it may crash the login flow

**Comment by louischan-oursky** [comment]
Problem 1: https://github.com/authgear/authgear-server/issues/3234

**Comment by fungc-io** [comment]
all fixed
