### ISSUE TITLE
open URL from SDK should use the domain got from server

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-sdk-js#248]
After applying custom domain
The authentication flow still work without changing the endpoint,
because it uses the domain retrieve from the server.

However the open settings page method is still using the endpoint. 
It will be great if it use the custom domain automatically, so it is not necessary for the user to update the app.

**Comment by joyzoursky** [comment]
Experiencing this issue when testing version update for Palace app.

I think this is a should-fix bug more than enhancement issue, as it is quite often that end-user will not always keep their apps updated, then on old version they will see the invalid redirect URI error from authgear.

**Comment by louischan-oursky** [comment]
- [ ] iOS SDK
- [ ] Android SDK
- [ ] React Native SDK
- [ ] Xamarin SDK
- [ ] Flutter SDK

**Comment by fungc-io** [comment]
tested, all is good
