### ISSUE TITLE
Develop and setup a SSR demo app for cookie based authentication

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-sdk-js#250]
In light of: https://github.com/authgear/authgear-deploy-production/issues/47
The SPA demo app is not compatible with the cookie-based authentication.
 
## Todo

- Create another demo app for cookie based authentication
- Endpoint should be fixed for the specific domain the demo app is hosted. It's displayed in the web app
- Client ID is not relevant, we should provide a default client ID. It's editable but prefilled by server environment config.
- "Is SSO Enabled" is always true
- Deploy the web app to the original QA site

**Comment by tung2744** [comment]
> Deploy the web app to the original QA site

I think I will create another one in pandawork instead of reusing the original site.

**Comment by tung2744** [comment]
@fungc-io Deployed here:
https://demo-cookie.authgear-qa-app.pandawork.com/

I also found some problem during setup, and created issue #3476

**Comment by fungc-io** [comment]
ok thanks

**Comment by fungc-io** [comment]
@tung2744 can we prefill the client id: `0d4866401a494ada` in the demo?

**Comment by fungc-io** [comment]
I've also updated the QA notes on notion about the URL change

**Comment by fungc-io** [comment]
done 👍
