### ISSUE TITLE
"Failed to fetch" in capacitor demo app

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-sdk-js#273]
When I pressed the "Authenticate" button on the capacitor app on Android,
It shows the following Error message

> # Error
>
> {"[contructor.name](http://contructor.name)":"TypeError","message":"Failed to fetch"}

![image](https://uploads.linear.app/860e83ae-05f0-4c4b-bd93-8a4b8d251836/9236c23c-c995-4a9a-9d1a-904621f939c8/a1debd1c-e5f8-4b16-b7cd-d88f57323ee0?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzg2MGU4M2FlLTA1ZjAtNGM0Yi1iZDkzLThhNGI4ZDI1MTgzNi85MjM2YzIzYy1jOTk1LTRhOWEtOWQxYS05MDQ2MjFmOTM5YzgvYTFkZWJkMWMtZTVmOC00YjE2LWI3Y2QtZDg4ZjU3MzIzZWUwIiwiaWF0IjoxNzA5OTE0NDU3LCJleHAiOjMzMjgwNDc0NDU3fQ.vLNj53Wn--ubhNiORBl3RecL2CxBoB7q_3VXgAGxyGc "=464x")

**Comment by IniZio** [comment]
@fung Couldn't reproduce this with `project-tomato-dev`, you were using same project as well?

**Comment by fungc-io** [comment]
@newman i've just tested with project-tomato-dev and it works
I was using `qa-ui-vtwo` on staging

**Comment by IniZio** [comment]
@fungc-io Can you invite me to `qa-ui-vtwo`? The invitation expired last time 🙇

**Comment by fungc-io** [comment]
invited 🙏

**Comment by IniZio** [comment]
@fung I fixed https://github.com/authgear/authgear-sdk-js/issues/273 by adding missing https://localhost to the redirect uris of "Ionic Demo"

https://docs.authgear.com/get-started/native-mobile-app/ionic-sdk#step-2-add-authorized-redirect-uris

**Comment by fungc-io** [comment]
🙆‍♂️ , thanks
capacitor is so weird..
