### ISSUE TITLE
[Feature request] Support opening the Account Deletion page directly via SDK

### ISSUE THREAD

**Issue by JasonNS1425** [authgear/authgear-sdk-js#286]
In the app we are working on, we would like to open the account deletion page directly when the user clicks the Delete Account button. Since the Authgear RN SDK `container.open()` only supports opening the Settings page and the Identities page, we can't do it natively with the Authgear SDK.

We have to work around by manually composing the URL ourselves or patching the package, but it seems more appropriate for Authgear to expose that page via the SDK to us.

[https://github.com/authgear/authgear-sdk-js/blob/5e34306/packages/authgear-core/src/types.ts#L345](https://github.com/authgear/authgear-sdk-js/blob/5e34306/packages/authgear-core/src/types.ts#L345)

## Requirements

* Open the Account Deletion page with an SDK call
* User can cancel the action and close the webview
* After deletion is confirmed, the user is disabled
  * the webview is closed and the user is logged out from the SDK.

**Comment by fungc-io** [comment]
Thanks @JasonNS1425, the idea is put into backlog. At the meantime you can use the admin api in your application's backend server to initiate account deletion.
